name: Notify on GitHub Pages Build

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get commit info via API
        id: commit
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }}"
          COMMIT_MSG=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL" | jq -r .commit.message)
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.event.workflow_run.head_sha }}"
          echo "msg=$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "url=$COMMIT_URL" >> $GITHUB_OUTPUT

      - name: Notify on Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ **GitHub Pages deployed successfully!**\n📝 **Commit:** ${{ steps.commit.outputs.msg }}\n🔗 [View Commit](${{ steps.commit.outputs.url }})\n🌐 Visit your site:\n- https://www.therealorco.org\n- https://www.therealorco.org/share\"}" $WEBHOOK_URL
