name: Notify on GitHub Pages Deploy

on:
  deployment_status:
    types: [success]

jobs:
  notify:
    runs-on: windows-latest
    if: github.event.deployment_status.environment == 'github-pages' && github.event.deployment_status.state == 'success'
    steps:
      - name: ✅ Send Discord Notification
        shell: cmd
        run: |
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"✅ GitHub Pages is live at https://www.therealorco.org/\"}" https://discord.com/api/webhooks/1372272241219338300/tVhBkjEM8jNofPecLR-sVqgKJllUZSy90tl86MRFR3Un7p-P_CiitTn24j-ynOwG-nQL
