name: Update Share Index (Windows Batch)

on:
  push:
    paths:
      - 'share/**'
      - 'generate_share_index.bat'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest commit message
        id: commitmsg
        shell: powershell
        run: |
          $msg = git log -1 --pretty=%B
          "msg=$msg" >> $env:GITHUB_OUTPUT

      - name: List directory contents
        run: dir

      - name: Run batch script to generate index.html
        run: .\generate_share_index.bat

      - name: Commit and push updated index.html
        shell: powershell
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add share/index.html
          try {
            git commit -m "${{ steps.commitmsg.outputs.msg }}"
          } catch {
            Write-Host "No changes to commit"
          }
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
